spring:
  datasource:
    url: jdbc:mysql://db:3306/sample?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: user
    password: password
    initialization-mode: always
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update

logging:
  level:
    org.springframework.web: DEBUG
